config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  root 'home#index'
  get 'all_albums', to: 'albums#all_albums'
  get 'draft_album', to: 'albums#draft_album'
  get 'published_album', to: 'albums#published_album'
  resources :albums do
    resources :likes
    collection do
      delete 'delete_image'
    end
  end
  resources :home do
    collection do
      match 'search' => 'home#search', via: %i[get post], as: :search
    end
  end
  get 'search', to: 'albums#search'
  resources :home
  resources :tags
end

app/models/album.rb
# frozen_string_literal: true

class Album < ApplicationRecord
  has_one_attached :cover_photo
  has_many_attached :photos
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
  validates :cover_photo, presence: true
  validates :photos, presence: true
  has_many :likes, dependent: :destroy
  validates :title, length: {
    minimum: 3,
    maximum: 10,
    tokenizer: ->(str) { str.scan(/\w+/) },
    too_short: 'must have at least %{count} words',
    too_long: 'must have at most %{count} words'
  }
  validates :description, length: {
    minimum: 3,
    maximum: 30,
    tokenizer: ->(str) { str.scan(/\w+/) },
    too_short: 'must have at least %{count} words',
    too_long: 'must have at most %{count} words'
  }

  def all_tags=(names)
    self.tags = names.split(',').map do |name|
      Tag.where(name: name).first_or_create!
    end
  end

  def all_tags
    tags.map(&:name).join(', ')
  end

  def to_param
    "#{id} #{title}".parameterize
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :album
  belongs_to :user
end

app/models/photo.rb
# frozen_string_literal: true

class Photo < ApplicationRecord
end

app/models/tag.rb
# frozen_string_literal: true

class Tag < ApplicationRecord
  has_many :taggings, dependent: :destroy
  has_many :albums, through: :taggings
end

app/models/tagging.rb
# frozen_string_literal: true

class Tagging < ApplicationRecord
  belongs_to :album
  belongs_to :tag
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :albums, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/albums_controller.rb
# frozen_string_literal: true

class AlbumsController < ApplicationController
  before_action :authenticate_user!

  def index
    @albums = current_user.albums
    @album = current_user.albums.count
  end

  def all_albums
    @albums = Album.where(published: true)
    @album = Album.where(published: true).count
    @user = User.all
  end

  def draft_album
    @albums = current_user.albums.where(published: false)
    @album_draft = current_user.albums.where(published: false).count
  end

  def published_album
    @albums = current_user.albums.where(published: true)
    @album = current_user.albums.where(published: true).count
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def create
    @album = current_user.albums.new(album_params)

    if @album.save
      redirect_to @album
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to @album
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy

    redirect_to root_path
  end

  def delete_image
    attachment = ActiveStorage::Attachment.find(params[:id])
    attachment.purge # or use purge_later
    redirect_back(fallback_location: albums_url)
  end

  private

  def album_params
    params.require(:album).permit(:title, :description, :published, :cover_photo, :all_tags, photos: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :to_param

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    redirect_to albums_path if user_signed_in?
    @q = Album.where(published: true).ransack(params[:q])
    @albums = @q.result.includes(:tags)
    @user = User.all
  end

  def search
    index
    render :index
  end

  def show
    @album = Album.find(params[:id])
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :find_album
  before_action :find_like, only: [:destroy]

  def create
    if already_liked?
      flash[:notice] = "You can't like more than once"
    else
      @album.likes.create(user_id: current_user.id)
    end
    redirect_to all_albums_path(@album)
  end

  def already_liked?
    Like.where(user_id: current_user.id, album_id: params[:album_id]).exists?
  end

  def destroy
    if !already_liked?
      flash[:notice] = 'Cannot unlike'
    else
      @like.destroy
    end
    redirect_to all_albums_path(@album)
  end

  def find_like
    @like = @album.likes.find(params[:id])
  end

  private

  def find_album
    @album = Album.find(params[:album_id])
  end
end

app/helpers/albums_helper.rb
# frozen_string_literal: true

module AlbumsHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/likes_helper.rb
# frozen_string_literal: true

module LikesHelper
end

app/views/albums/_form.html.erb
<%=form_with model: album do |form|%> 
<% if album.errors.full_messages.any? %>
<% album.errors.full_messages.each do |error_message| %> 
<%= error_message if album.errors.full_messages.first == error_message %> <br />
<% end %> 
<% end %>
<div>
  <%=form.label :title%> <%=form.text_field :title,class:'form-control'%>
</div>
<br />
<div>
  <%=form.label :cover_photo%> 
  <%=form.file_field:cover_photo,class:'form-control'%>
</div>
<br />
<div>
  <%=form.label :description%> 
  <%=form.text_area:description,class:'form-control'%>
</div>
<br />
<div>
  <%=form.label :tag %> 
  <%=form.text_area :all_tags,class:'form-control' %>
</div>
<br />
<div>
  <%=form.label :photos%> 
  <%=form.file_field:photos,class:'form-control',:multiple => true%>
</div>
<br />
  <%# if album.published %>
   <%form.hidden_field(:published)%>
    <%# else %>
<div>
  <%=form.label :published%> 
  <%=form.check_box :published%>
</div>
<br />
<%#end%>
<div><%=form.submit%></div>

<%end%>
<br />

app/views/albums/_photos_form.html.erb
<h2>Add more Photos</h2>
<%=form_with model: @album do |form|%>
<div>
  <%=form.label :photos%> 
  <%=form.file_field:photos,class:'form-control',:multiple => true%>
</div>
<br />
<div><%=form.submit%></div>
<%end%>
<br />

app/views/albums/_photos_show.html.erb
<h1>Photos</h1>
<div class="row">
  <%@album.photos.each do |image|%>
  <div class="col-md-3">
    <div class="card">
      <div class="card-header">
        <%= link_to image do %>
        <i class="fas fa-expand-wide green"></i>
        <%end %> 
        <%= link_to delete_image_albums_path(id: image.id),method: :delete, data: { confirm: "Are you sure?" } do %>
        <i class="fas fa-times right"></i>
        <%end%>
      </div>
      <div class="card-body">
        <%= image_tag(image,class:"card-top-img img-fluid") %>
      </div>
    </div>
  </div>
  <%end%>
</div>

app/views/albums/all_albums.html.erb
<h1>All Published Albums Of all Users are <%=@album%></h1>
<div class="row">
  <% @user.each do |user| %>
    <% @albums.each do |album| %>
      <%if user.id == album.user_id %>
        <div class="col-md-4">
          <div class="card">
            <div class="card-header">
              <strong>Name:</strong>
              <%=user.name%>
            </div>
            <div class="card-body">
              <% if album.cover_photo.attached? %>
                <%=link_to home_path(id: album.id) do%>
                  <%=image_tag(album.cover_photo,class: " img-fluid") %>
                <%end%> <%end%>
            </div>
            <div class="card-footer text-center">
            <a data-bs-toggle="collapse" href="#album-<%= album.id %>"  data-toggle="collapse"role="button" aria-expanded="false" ><i class="fa fa-arrow-circle-down" style="font-size:23px"></i></a>
            </div>
            <section class="collapse multi-collapse" id="album-<%= album.id%>">
              <div class="card-footer">
                <span>
                  <strong>Title:</strong>
                  <%=album.title%>
                </span>a
                <span class="pl">
                  <strong>Description:</strong>
                  <%=album.description%>
                </span>
              </div>
              <div class="card-footer">
                <span>
                  <strong>Tags:</strong>
                  <%=album.all_tags %>
                </span>
                <span class="pl">
                  <strong>Total Photos:</strong>
                  <%=album.photos.count%>
                </span>
              </div>
            </section>
          </div>
        </div>
      <%end%>
    <%end%>
  <%end%>
</div>

app/views/albums/draft_album.html.erb
<h1>All Draft Album of <%=current_user.name%> are <%=@album_draft%></h1>
<div class="row">
  <% @albums.each do |album| %>
    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          <%= link_to album_path(album),method: :delete, data: { confirm: "Are you sure?" } do   %>
            <i class="fas fa-times right"></i>
          <%end %>
          <%= link_to edit_album_path(album)do   %>
            <i class="fas fa-edit green"></i>
          <%end %>
        </div>
        <div class="card-body">
          <% if album.cover_photo.attached? %>
            <%= link_to  home_path(id: album.id),class:"link" do%>
              <%=image_tag(album.cover_photo,class: "card-top-img img-fluid") %>
            <%end%> <%end%>
        </div>
        <div class="card-footer text-center">
          <a data-bs-toggle="collapse" href="#album-<%= album.id %>"  role="button" aria-expanded="false" ><i class="fa fa-arrow-circle-down" style="font-size:23px"></i></a>
        </div>
        <section class="collapse multi-collapse" id="album-<%= album.id%>">
          <div class="card-footer">
            <span>
              <strong>Title:</strong>
              <%=album.title%>
            </span>
            <span class="pl">
              <strong>Description:</strong>
              <%=album.description%>
            </span>
          </div>
          <div class="card-footer">
            <span>
              <strong>Tags:</strong>
              <%=album.all_tags %>
            </span>
            <span class="pl">
              <strong>Total Photos:</strong>
              <%=album.photos.count%>
            </span>
          </div>
        </section>
      </div>
    </div>
  <%end%>
</div>

app/views/albums/edit.html.erb
<h1>Edit Album</h1>

<%= render "form", album: @album%> 
<%=link_to "Back" , root_path, class:'btn btn-secondary'%>

app/views/albums/index.html.erb
<h1>All Albums of <%=current_user.name%> are <%=@album%></h1>
<div class="row">
  <% @albums.each do |album| %>
    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          <%= link_to album_path(album),method: :delete, data: { confirm: "Are you sure?" } do   %>
            <i class="fas fa-times right"></i>
          <%end %>
          <%= link_to edit_album_path(album)do   %>
            <i class="fas fa-edit green"></i>
          <%end %>
        </div>
        <div class="card-body">
          <% if album.cover_photo.attached? %>
            <%= link_to album,class:"link" do%>
              <%=image_tag(album.cover_photo,class: "card-top-img img-fluid") %>
            <%end%> <%end%>
        </div>
        <div class="card-footer text-center">
          <a data-bs-toggle="collapse" href="#album-<%= album.id %>" role="button" aria-expanded="false" ><i class="fa fa-arrow-circle-down" style="font-size:23px"></i></a>
        </div>
        <section class="collapse multi-collapse" id="album-<%= album.id%>">
          <div class="card-footer">
            <span>
              <strong>Title:</strong>
              <%=album.title%>
            </span>
            <span class="pl">
              <strong>Description:</strong>
              <%=album.description%>
            </span>
          </div>
          <div class="card-footer">
            <span>
              <strong>Tags:</strong>
              <%=album.all_tags %>
            </span>
            <span class="pl">
              <strong>Total Photos:</strong>
              <%=album.photos.count%>
            </span>
          </div>
        </section>
      </div>
    </div>
  <%end%>
</div>

app/views/albums/new.html.erb
<h1>New Album</h1>
<%= render "form", album: @album%>

app/views/albums/published_album.html.erb
<h1>All Publish Album of <%=current_user.name%> are <%=@album%></h1>
<div class="row">
  <% @albums.each do |album| %>
    <div class="col-md-4">
      <div class="card">
        <div class="card-header">
          <%= link_to album_path(album),method: :delete, data: { confirm: "Are you sure?" } do   %>
            <i class="fas fa-times right"></i>
          <%end %>
          <%= link_to edit_album_path(album)do   %>
            <i class="fas fa-edit green"></i>
          <%end %>
        </div>
        <div class="card-body">
          <% if album.cover_photo.attached? %>
            <%= link_to album,class:"link" do%>
              <%=image_tag(album.cover_photo,class: "card-top-img img-fluid") %>
            <%end%> <%end%>
        </div>
        <div class="card-footer text-center">
          <a data-bs-toggle="collapse"  href="#album-<%= album.id %>" role="button" aria-expanded="false" ><i class="fa fa-arrow-circle-down" style="font-size:23px"></i></a>
        </div>
        <section class="collapse multi-collapse" id="album-<%= album.id%>">
          <div class="card-footer">
            <span>
              <strong>Title:</strong>
              <%=album.title%>
            </span>
            <span class="pl">
              <strong>Description:</strong>
              <%=album.description%>
            </span>
          </div>
          <div class="card-footer">
            <span>
              <strong>Tags:</strong>
              <%=album.all_tags %>
            </span>
            <span class="pl">
              <strong>Total Photos:</strong>
              <%=album.photos.count%>
            </span>
          </div>
        </section>
      </div>
    </div>
  <%end%>
</div>

app/views/albums/show.html.erb
<h1>Album</h1>
<p id="notice"><%= notice%></p>
<div class="col-md-12">
  <div class="card">
    <div class="card-body">
      <% if @album.cover_photo.attached? %>
        <%=image_tag(@album.cover_photo,class: "card-top-img img-fluid") %>
      <%end%>
    </div>
    <div class="card-footer text-center">
      <a data-bs-toggle="collapse"  href="#album"  role="button" aria-expanded="false" ><i class="fa fa-arrow-circle-down" style="font-size:23px"></i></a>
    </div>
    <section class="collapse multi-collapse" id="album">
      <div class="card-footer">
        <span>
          <strong>Title:</strong>
          <%=@album.title%>
        </span>
        <span class="pl">
          <strong>Description:</strong>
          <%=@album.description%>
        </span>
      </div>
      <div class="card-footer">
        <span>
          <strong>Tags:</strong>
          <%=@album.all_tags %>
        </span>
        <span class="pl">
          <strong>Total Photos:</strong>
          <%=@album.photos.count%>
        </span>
      </div>
    </section>
  </div>
</div>
<%=render 'photos_show'%>
<div class="text-center my-4">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Add Photos
  </button>
  <span class="mx-3"><%= link_to "Back", root_path,class: "btn btn-secondary"%></span>
</div>
<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Photos</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <%=form_with model: @album do |form|%>
          <% if @album.errors.full_messages.any? %>
            <% @album.errors.full_messages.each do |error_message| %>
              <%= error_message if @album.errors.full_messages.first == error_message %> <br />
            <% end %>
          <% end %>
          <div>
            <%=form.label :photos%>
            <%=form.file_field:photos,class:'form-control',:multiple => true ,:required => true%>
          </div>
          <br />
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          <%= form.submit "Add Photos", type: "submit", :class=> "btn btn-primary" %>
        <%end%>
      </div>
    </div>
  </div>
</div>

app/views/home/_search.html.erb
<div class="container mt-3">
  <%= search_form_for @q, url: search_home_index_path,
                          html: { method: :post } do |f| %>
     <%= f.search_field :tags_name_eq %> 
     <%=f.submit "search" %> <% end %>
  </div>

app/views/home/index.html.erb
<%=render 'home/search'%>
<h1>All Published Albums</h1>
<div class="container-fluid">
  <div class="row">
    <% @user.each do |user| %>
      <% @albums.each do |album| %>
        <%if user.id == album.user_id %>
          <div class="col-md-4">
            <div class="card">
              <div class="card-header">
                <strong>Name:</strong>
                <%=user.name%>
              </div>
              <div class="card-body">
                <%= link_to  home_path(id: album.id),class:"link" do%>
                  <% if album.cover_photo.attached? %>
                    <%= image_tag(album.cover_photo,class: "card-top-img img-fluid") %>
                  <% end %>
                <%end%>
              </div>
              <div class="card-footer text-center">
                <a data-bs-toggle="collapse" href="#album-<%= album.id %>" role="button" aria-expanded="false" ><i class="fa fa-arrow-circle-down" style="font-size:23px"></i></a>
              </div>
              <section class="collapse multi-collapse" id="album-<%= album.id%>">
                <div class="card-footer">
                  <span>
                    <strong>Title:</strong>
                    <%=album.title%>
                  </span>
                  <span class="pl">
                    <strong>Description:</strong>
                    <%=album.description%>
                  </span>
                </div>
                <div class="card-footer">
                  <span>
                    <strong>Tags:</strong>
                    <%=album.all_tags %>
                  </span>
                  <span class="pl">
                    <strong>Total Photos:</strong>
                    <%=album.photos.count%>
                  </span>
                </div>
              </section>
            </div>
          </div>
        <% end %>
      <% end %>
    <%end%>
  </div>
</div>

app/views/home/show.html.erb
<div class="row">
  <%@album.photos.each do |image|%>
    <div class="col-md-3">
      <div class="card">
        <div class="card-header">
          <%= link_to image do %>
            <i class="fas fa-expand-wide green"></i>
          <%end %>
        </div>
        <div class="card-body">
          <%= image_tag(image,class:"card-top-img img-fluid") %>
        </div>
      </div>
    </div>
  <%end%>
</div>
<%if user_signed_in?%>
  <div class="my-4">
    <%= link_to "Back", all_albums_path, class: "btn btn-secondary mx-2" %>
  </div>
<%else %>
  <div class="my-4">
    <%= link_to "Back", root_path, class: "btn btn-secondary mx-2" %>
  </div>
<%end%>

app/views/layouts/_footer.html.erb
<div class="container-fluid  bg-body  fixed-bottom bg animate">
  <div class="row ">
    <div class="col-md-12 text-center">
      <h1>ᴜɴɪᴠᴇʀsᴇ</h1>
      <h5>This Website was designed by universe</h5>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6 text-center">
      <h6>privacy policy | Terms of use</h6>
    </div>
    <div class="col-md-6 text-center">
      <h6>&copy;2021-2026 universe.com</h6>
    </div>
  </div>
</div>

app/views/layouts/_header.html.erb
<div class="container-fluid bg-dark shadow-lg p-3 mb-5 bg-body rounded fixed-top bg animate">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="/">
        <i class="fas fa-globe-asia"></i>
        ᴜɴɪᴠᴇʀsᴇ
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto">
          <%= link_to root_path, class: "nav-link #{'active fw-bold' if current_page?(albums_path)}" do %>
            <div class="fa fa-home"></div>
            Home
          <% end %>
          <%= link_to new_album_path, class: "nav-link #{'active fw-bold' if current_page?(new_album_path,class:"link")}" do %>
            <div  class="fas fa-images"></div>
            New Album 
          <% end %>
          <%if user_signed_in?%>
            <%= link_to all_albums_path, class: "nav-link #{'active fw-bold' if current_page?(all_albums_path)}" do %>
              <div  class="fas fa-images"></div>
              All Album 
            <% end %>
            <%= link_to published_album_path, class: "nav-link #{'active fw-bold' if current_page?(published_album_path)}" do %>
              <div  class="fas fa-images"></div>
              Published Album
            <% end %>
            <%= link_to draft_album_path, class: "nav-link #{'active fw-bold' if current_page?(draft_album_path)}" do %>
              <div  class="fas fa-images"></div>
              Draft Album
            <% end %>
          <%end%>
        </ul>
        <ul class="navbar-nav ms-auto">
          <% if current_user %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                <div class="fa fa-user"></div>
                <b><%= current_user.email %></b>
              </a>
              <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to edit_user_registration_path, class: "dropdown-item #{'active fw-bold' if current_page?(edit_user_registration_path)}" do %>
                  <div class="fa fa-cog"></div>
                  <b>Account settings</b>
                <% end %>
                <%= link_to destroy_user_session_path, method: :delete, class: "dropdown-item" do %>
                  <b>Sign out</b>
                <% end %>
              </ul>
            </li>
          <% else %>
            <%= link_to "Log in", new_user_session_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_session_path)}" %>
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link #{'active fw-bold' if current_page?(new_user_registration_path)}" %>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>
  <div class="container-fluid alt">
    <% if notice %>
      <p class="alert alert-success alert-dismissible fade show" role="alert"><%= notice %></p>
    <% end %> <% if alert %>
      <p class="alert alert-danger alert-dismissible fade show" role="alert"><%= alert %></p>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%=render 'layouts/header'%>
    <div class="container gap">
      <%= yield %>
      <hr>
    </div>
    <%=render 'layouts/footer'%>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>